@startuml
title Half-Pedal Compatibility Mode
start
:Read Sustain Pedal mV;
if (mV < Lower Limit?) then (Yes)
  :Output 0V;
elseif (mV > Upper Limit?) then (Yes)
  :Output Max Voltage;
else (No)
  :Output Half-Pedal Voltage;
endif
stop
@enduml
